Adopt commit a1209d1a7 from master: Merge pull request #1088 from sthursfield/gcc7-warnings-fixes
commit a1209d1a7ef1e1c8d6ffdadcf89802941557d295
Merge: 37fb41374 0792c8ba3
Author: Henry Verschell <hverschell@bloomberg.net>
Date:   Thu May 18 15:51:12 2017 -0400

    Merge pull request #1088 from sthursfield/gcc7-warnings-fixes

    Fix new compile warnings that appear with GCC 7

commit 0792c8ba3a0b359896c7ea92c8b1898f24f7b0e8
Author: Sam Thursfield <sthursfield@bloomberg.net>
Date:   Fri Apr 21 08:32:37 2017 -0400

    Fix "enum constant in boolean context" warnings

    These appear with GCC 7, and look like this:

        groups/bdl/bdlb/bdlb_variant.h: In instantiation of 'struct BloombergLP::bdlb::Variant_TypeIndex<BloombergLP::bslmf::TypeList<long long int, double, bsl::basic_string<char, std::char_traits<char>, bsl::allocator<char> >, BloombergLP::bdlt::DatetimeTz, bsl::vector<char, bsl::allocator<char> > >, BloombergLP::bslma::Allocator*>':
        groups/bdl/bdlb/bdlb_variant.h:7115:79: required from 'BloombergLP::bdlb::VariantImp<TYPES>::VariantImp(const TYPE_OR_ALLOCATOR&) [with TYPE_OR_ALLOCATOR = BloombergLP::bslma::Allocator*; TYPES = BloombergLP::bslmf::TypeList<long long int, double, bsl::basic_string<char, std::char_traits<char>, bsl::allocator<char> >, BloombergLP::bdlt::DatetimeTz, bsl::vector<char, bsl::allocator<char> > >]'
        groups/bdl/bdlb/bdlb_variant.h:8064:23: required from 'BloombergLP::bdlb::Variant<TYPES>::Variant(const TYPE_OR_ALLOCATOR&) [with TYPE_OR_ALLOCATOR = BloombergLP::bslma::Allocator*; TYPES = {long long int, double, bsl::basic_string<char, std::char_traits<char>, bsl::allocator<char> >, BloombergLP::bdlt::DatetimeTz, bsl::vector<char, bsl::allocator<char> >}]'
        groups/bal/ball/ball_userfieldvalue.h:329:25: required from here
        groups/bdl/bdlb/bdlb_variant.h:5915:10: error: enum constant in boolean context [-Werror=int-in-bool-context]

commit c35ecb0931c61d3620358f38f132605e5b393b0c
Author: Sam Thursfield <sthursfield@bloomberg.net>
Date:   Mon Apr 10 07:05:20 2017 -0400

    Add casts to fix type conversion warnings

    In particular this warning:

            ../../groups/bsl/bslstl/bslstl_hashtable.cpp: In static member function 'static size_t BloombergLP::bslstl::HashTable_ImpDetails::growBucketsForLoadFactor(size_t*, size_t, size_t, double)':
            ../../groups/bsl/bslstl/bslstl_hashtable.cpp:79:28: error: conversion to 'double' from 'size_t {aka long unsigned int}' may alter its value [-Werror=conversion]
                     if (minElements <= newCapacity) {
                                        ^~~~~~~~~~~
            cc1plus: all warnings being treated as errors

commit 8fac8c6d91a2bc4ed75f2f93e2c0316bc75631ab
Author: Sam Thursfield <sthursfield@bloomberg.net>
Date:   Mon Apr 10 07:05:15 2017 -0400

    Add case fall-through annotation comments

    These silence the new -Wimplicit-fallthrough warning that has been
    introduced with GCC 7.

commit e9792c6b804e7d29e86ab62da9174ee9229cf34f
Author: Sam Thursfield <sthursfield@bloomberg.net>
Date:   Mon Apr 10 07:05:10 2017 -0400

    Remove unused variable ctIt

    Fixes this warning:

            ../../groups/bal/balm/balm_publicationscheduler.cpp: In member function 'std::ostream& BloombergLP::balm::PublicationScheduler::print(std::ostream&, int, int) const':
            ../../groups/bal/balm/balm_publicationscheduler.cpp:720:52: error: variable 'ctIt' set but not used [-Werror=unused-but-set-variable]
                     bsl::set<const Category *>::const_iterator ctIt =
                                                                ^~~~
            cc1plus: all warnings being treated as errors