Silence unused variable warning in bslstl::HashTable_Util
Hit this with clang on macOS:

```
/usr/local/Cellar/bsl-internal/3.5.0.0/include/bslstl_hashtable.h:3754:52: error: unused parameter 'ptr' [-Werror,-Wunused-parameter]
```