Fix "enum constant in boolean context" warnings
These appear with GCC 7, and look like this:

    groups/bdl/bdlb/bdlb_variant.h: In instantiation of 'struct BloombergLP::bdlb::Variant_TypeIndex<BloombergLP::bslmf::TypeList<long long int, double, bsl::basic_string<char, std::char_traits<char>, bsl::allocator<char> >, BloombergLP::bdlt::DatetimeTz, bsl::vector<char, bsl::allocator<char> > >, BloombergLP::bslma::Allocator*>':
    groups/bdl/bdlb/bdlb_variant.h:7115:79: required from 'BloombergLP::bdlb::VariantImp<TYPES>::VariantImp(const TYPE_OR_ALLOCATOR&) [with TYPE_OR_ALLOCATOR = BloombergLP::bslma::Allocator*; TYPES = BloombergLP::bslmf::TypeList<long long int, double, bsl::basic_string<char, std::char_traits<char>, bsl::allocator<char> >, BloombergLP::bdlt::DatetimeTz, bsl::vector<char, bsl::allocator<char> > >]'
    groups/bdl/bdlb/bdlb_variant.h:8064:23: required from 'BloombergLP::bdlb::Variant<TYPES>::Variant(const TYPE_OR_ALLOCATOR&) [with TYPE_OR_ALLOCATOR = BloombergLP::bslma::Allocator*; TYPES = {long long int, double, bsl::basic_string<char, std::char_traits<char>, bsl::allocator<char> >, BloombergLP::bdlt::DatetimeTz, bsl::vector<char, bsl::allocator<char> >}]'
    groups/bal/ball/ball_userfieldvalue.h:329:25: required from here
    groups/bdl/bdlb/bdlb_variant.h:5915:10: error: enum constant in boolean context [-Werror=int-in-bool-context]