Remove unused variable ctIt
Fixes this warning:

	../../groups/bal/balm/balm_publicationscheduler.cpp: In member function 'std::ostream& BloombergLP::balm::PublicationScheduler::print(std::ostream&, int, int) const':
	../../groups/bal/balm/balm_publicationscheduler.cpp:720:52: error: variable 'ctIt' set but not used [-Werror=unused-but-set-variable]
		 bsl::set<const Category *>::const_iterator ctIt =
							    ^~~~
	cc1plus: all warnings being treated as errors